- name: Deploy Application to Kubernetes with Namespaces
  hosts: all
  become: yes
  vars:
    app_port: "{{ '8002' if env_type == 'dev' else '8003' }}"
    unit_name: "k8s-proxy-{{ '8002' if env_type == 'dev' else '8003' }}.service"

  tasks:
    - name: Ensure Namespace exists for {{ env_type }}
      shell: kubectl create namespace {{ env_type }} || true

    - name: Copy manifests and Apply
      copy:
        src: "k8s/{{ env_type }}.yaml"
        dest: "/root/task3/k8s/{{ env_type }}.yaml"

    - name: Update and Apply manifest
      shell: |
        sed -i "s|DOCKER_IMAGE_TAG|{{ docker_user }}/my-app:{{ app_version }}|g" /root/task3/k8s/{{ env_type }}.yaml
        kubectl apply -f /root/task3/k8s/{{ env_type }}.yaml -n {{ env_type }}

    - name: Open Firewall ports
      ufw:
        rule: allow
        port: "{{ app_port }}"
        proto: tcp

    - name: Setup Indestructible Port Forwarding
      shell: |
        PORT="{{ app_port }}"
        systemctl stop "{{ unit_name }}" || true
        systemctl reset-failed "{{ unit_name }}" || true
        
        systemd-run --unit="k8s-proxy-{{ app_port }}" \
          --setenv=KUBECONFIG=/root/.kube/config \
          --setenv=HOME=/root \
          /usr/bin/kubectl port-forward \
          --address 0.0.0.0 \
          service/service-{{ env_type }} {{ app_port }}:80 \
          -n {{ env_type }}
      args:
        executable: /bin/bash
