apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-release
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app
      env: release
  template:
    metadata:
      labels:
        app: my-app
        env: release
    spec:
      containers:
      - name: app
        image: DOCKER_IMAGE_TAG
        ports:
        - containerPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: service-release
spec:
  type: ClusterIP
  selector:
    app: my-app
    env: release
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8000
