- name: Install Kubernetes components for babiichuk
  hosts: k8s_nodes
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, conntrack, socat, docker.io]
        state: present

    - name: Download and Install Minikube
      shell: |
        curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        install minikube /usr/local/bin/
        rm minikube
      args:
        creates: /usr/local/bin/minikube

    - name: Download and Install kubectl
      shell: |
        curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl
        rm kubectl
      args:
        creates: /usr/local/bin/kubectl

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Fix Minikube permissions and start
      shell: |
        chmod +x /usr/local/bin/minikube
        minikube start --driver=none --listen-address=0.0.0.0 --force
      register: minikube_res
