- name: Install Kubernetes components for babiichuk
  hosts: k8s_nodes
  become: yes
  tasks:
    - name: Update apt cache
      apt: update_cache=yes

    - name: Install dependencies
      apt:
        name: [apt-transport-https, ca-certificates, curl, conntrack, socat, docker.io]
        state: present

    - name: Download Minikube binary
      get_url:
        url: https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
        dest: /usr/local/bin/minikube
        mode: '0755'

    - name: Download kubectl binary
      get_url:
        url: "https://dl.k8s.io/release/stable.txt"
        dest: /tmp/k8s_version.txt
        mode: '0644'

    - name: Install kubectl
      shell: |
        VERSION=$(cat /tmp/k8s_version.txt)
        curl -LO "https://dl.k8s.io/release/${VERSION}/bin/linux/amd64/kubectl"
        install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl

    - name: Install Helm
      shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
      args:
        creates: /usr/local/bin/helm

    - name: Start Minikube (None driver for cloud VM)
      shell: minikube start --driver=none --listen-address=0.0.0.0
      register: minikube_res
      changed_when: "'Done!' in minikube_res.stdout"
